Rails:
  Enabled: true

AllCops:
  Exclude:
  - 'bin/*'
  - 'node_modules/**/*'
  - 'db/schema.rb'
Style/ClassAndModuleChildren:
  Enabled: false
Style/RegexpLiteral:
  EnforcedStyle: slashes
Style/Documentation:
  Exclude:
    - 'db/migrate/*'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
Metrics/AbcSize:
  Exclude:
  - 'db/migrate/*'