language: ruby
rvm:
  - 2.4.4

cache:
  directories:
    - vendor/bundle
    - node_modules

bundler_args: --without production

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails test
